### ISSUE TITLE
Dual Weapons not displayed + Char select combat to idle stance.

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#122]
Dual Daggers: Top is browser, bottom is client
![image](https://user-images.githubusercontent.com/214579/194753632-76a64ec8-e564-4e59-86b9-be24cc9666fa.png)

On Client, if a sword is equipped in the right hand and a dagger in the left hand, only the sword will be displayed like in the bottom example in the above picture but if reversed, both weapons will display, one being the dagger and the other a sword like in the picture below and we can see that both weapons do stack on the same hand.

![image](https://user-images.githubusercontent.com/214579/194754055-7a572373-16ec-49c3-9c53-e44a4e3ed589.png)

In char select, chars should be idle and not in combat stance and it's funny to see both weapons displayed there and it seems like a nice feature to keep though :)
![image](https://user-images.githubusercontent.com/214579/194754243-047ddd0d-b6ee-402d-86ee-b11c89202e79.png)

**Comment by mrunzo** [comment]
I am on this and will make a PR when it is completed.

**Comment by MrAntares** [comment]
I already added the types and names to [WeaponType](https://github.com/MrAntares/Ragna.roBrowser/blob/master/src/DB/Items/WeaponType.js) (25-30) and https://github.com/MrAntares/Ragna.roBrowser/blob/master/src/DB/Items/WeaponTable.js

The only issue I had that these types are "made up types". You have to check right and left hand and alter the sprite type according. It is not as easy as just displaying the right and left hand sprite, because dual weapons are actually right hand only sprites. The right hand has to be owerwritten with a dual hand sprite and the left hand sprite just set to nothing. I tried making it but the DB function is not quite ready for it and it needed some rework that I didn't have the time for. Also, be aware that there is only one way sprite for different type weapons like sword+axe and axe+sword both uses the sword+axe type, because there is no reverse type.

**Comment by mrunzo** [comment]
actually, I have done this on my old NW.js client but I notice some bugs when login into the game the first time.
![image](https://user-images.githubusercontent.com/6884575/204152903-2368a750-c8eb-4a99-bc07-eda4c8487918.png)
![image](https://user-images.githubusercontent.com/6884575/204152910-8a429cb3-8781-41cb-b508-b5d8e1642c54.png)
![image](https://user-images.githubusercontent.com/6884575/204152930-a26962cd-84a6-498c-8db3-1d2203ad0a6d.png)

I also did the weapon inspection (i don't know how to call it but it is like a knife blade slash when attacking)

**Comment by mrunzo** [comment]
weapon slash is also done.
![image](https://user-images.githubusercontent.com/6884575/204153097-9e1217aa-dc0a-4ac7-8ab5-85d0150de211.png)
![image](https://user-images.githubusercontent.com/6884575/204153116-2736c2bc-88b1-4629-9d7c-ebd921dc4c01.png)

**Comment by alisonrag** [comment]
implemented at:
https://github.com/MrAntares/roBrowserLegacy/commit/f39e615989b2d515d8e3bace89364b1d864de52d
