### ISSUE TITLE
Equipment Info

### ISSUE THREAD

**Issue by samtigall** [MrAntares/roBrowserLegacy#389]
**Missing feature**
Right Click > Check Equipment Info doesnt show

**Comment by MrAntares** [comment]
We receive the packet, but the function that handles it is empty, because I couldn't clone properly the Equipment window without it breaking everything. We probably need to touch the cloning so it won't cause conflicts. Right now if we do a shallow clone it's just not enough, because we need to redo every function that is needed for the window to work, and if we do a deep clone it will just keep all the function references to the original object, causing a ton of conflicts.

**Comment by Samuel23** [comment]
It really needs UI like the Equipment just without the other functions

I am almost done implementing it on my side though tested only for latest packet 0xb37 for PACKETVER >= 20200916

V0
![image](https://github.com/MrAntares/roBrowserLegacy/assets/4675631/133e1dd6-6c55-4fe5-8dcc-9137ce4ba5e8)

V1
![image](https://github.com/MrAntares/roBrowserLegacy/assets/4675631/56b701d8-a200-4c5e-9b81-2d8647632a0d)
![image](https://github.com/MrAntares/roBrowserLegacy/assets/4675631/7509453e-bce8-40b0-8989-f49fee0d56d4)

V2
![image](https://github.com/MrAntares/roBrowserLegacy/assets/4675631/57199f87-2620-4f86-9059-c4ed7e1e79b3)

**Comment by Boblee-D-Dev** [comment]
I try on packetver 20190625 , i got an error
![Uploading Screenshot 2567-06-30 at 22.16.40.png…]()

**Comment by alisonrag** [comment]
implemented at #413
